import "./globals.css";
import type { Metadata } from "next";
import GlobalStyles from "./global_styles/main.module.scss";
import Nav from "./global_components/Nav";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={GlobalStyles.global}>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  );
}
